### ISSUE TITLE
Question Regarding KakaoPage Crawler in dev/3.0.0 Branch

### ISSUE THREAD

**Issue by shalin-okada** [HyeokjaeLee/korea-webtoon-api#32]
I apologize for the abrupt question.

I noticed that the main branch includes a crawler for KakaoPage, but in the dev/3.0.0 branch, the code seems to be separated.
Is this because you've decided to manage it separately, or is it due to changes in KakaoPage's specifications that made crawling more difficult?

In fact, the crawler for KakaoPage does not work with the code in the main branch.
I am keen on crawling KakaoPage and just happened to come across your repository today.
I'm hoping, if possible, to find a working solution for this.

**Comment by HyeokjaeLee** [comment]
This is because the information on the Kakao page has changed.
I won't be able to update it for a while.

**Comment by shalin-okada** [comment]
Thanks for the answer.
I'll look forward to your updates while I find my own crawling method.
